### ISSUE TITLE
Voice/StreamIntent.js:6 error

### ISSUE THREAD

**Issue by haoji** [chalda/DiscordBot#14]
When I do "node discord_bot.js" I get:

DiscordBot/node_modules/discord.js/lib/Voice/StreamIntent.js:6
f (typeof superClass !== "function" && superClass !== null) { throw new TypeEr
                                                                    ^
TypeError: Super expression must either be null or a function, not object
    at _inherits (DiscordBot/node_modules/discord.js/lib/Voice/StreamIntent.js:6:113)
    at DiscordBot/node_modules/discord.js/lib/Voice/StreamIntent.js:11:2
    at Object.<anonymous> (DiscordBot/node_modules/discord.js/lib/Voice/StreamIntent.js:20:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (DiscordBot/node_modules/discord.js/lib/Voice/VoiceConnection.js:20:20)

I'm running Ubuntu LTS

**Comment by haoji** [comment]
I was using wrong NodeJS version. 

Installing Node.js v0.12 Debian / Ubuntu repository

# Note the new setup script name for Node.js v0.12
curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -

# Then install with:
sudo apt-get install -y nodejs
