### ISSUE TITLE
Config for IMGFLIP ?

### ISSUE THREAD

**Issue by snaildos** [chalda/DiscordBot#146]
Hey there. I need some help with the config for IMGFLIP. I have put in my username and password as like this:
        "imgflip_username": "snaildos",
        "imgflip_password": "mypassword",
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Please help me with this. I want to know if it is set out like this?
Many thanks.
- SnailDOS

**Comment by Androz2091** [comment]
Yes, you don't need the baseURL like in the auth.json.example

**Comment by snaildos** [comment]
@Androz2091 What do you think a solution could be?

**Comment by chalda** [comment]
i think you need to include top and bottom text?

**Comment by snaildos** [comment]
@chalda 
treating /meme yee "yee" "yee" from <@583483419078688769> as command
{ '0': Error: No texts specified. Remember, API request params are http parameters not JSON.
    at Request._callback (/home/server/DiscordBot/node_modules/imgflipper/index.js:46:10)
    at Request.self.callback (/home/server/DiscordBot/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/server/DiscordBot/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/server/DiscordBot/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) }
undefined

**Comment by chalda** [comment]
aight might actually just be broken then :D ill take a look prolly
just need to update the deps

**Comment by snaildos** [comment]
So, what do i do?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by F9Alejandro** [comment]
just wait a little bit for someone to fix it for ya ;)

**Comment by snaildos** [comment]
K

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snaildos** [comment]
Ye it's annoying because I need it rn. So, What really is the problem...?
