### ISSUE TITLE
Cannot send messages to this user

### ISSUE THREAD

**Issue by AkgunFatih** [chalda/DiscordBot#152]
```
Starting DiscordBot
Node version: v12.15.0
Discord.js version: 11.6.4
logging in with token
Logged in! Currently serving 1 servers.
Loaded 64 chat commands
Type !help on Discord for a command list.
treating !help from <@411524639869894657> as command
DiscordAPIError: Cannot send messages to this user
    at /root/discord/DiscordBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15
    at /root/discord/DiscordBot/node_modules/snekfetch/src/index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  name: 'DiscordAPIError',
  message: 'Cannot send messages to this user',
  path: '/api/v7/channels/702283893650489344/messages',
  code: 50007,
  method: 'POST'
```

**Comment by F9Alejandro** [comment]
with out any code to see what it is you are trying to send we will be unable to assist you.

**Comment by AkgunFatih** [comment]
@F9Alejandro first i started the bot 
then as soon as i send the !help command
the bot crashes

**Comment by F9Alejandro** [comment]
did you follow the instructions on how to make a bot login? you won't be able to use your normal login to act as a bot.

**Comment by valkyrienyanko** [comment]
Discord gives you the option to block DMs from anything and everyone. The bot is trying to send a message to someone who's blocking all incoming DMs.
