### ISSUE TITLE
Launch issue

### ISSUE THREAD

**Issue by juhamoo** [chalda/DiscordBot#21]
Hi,

Not sure what's causing this one:

 % node discord_bot.js

/home/bot/git/DiscordBot/node_modules/discord.js/lib/Voice/StreamIntent.js:9
f (typeof superClass !== "function" && superClass !== null) { throw new TypeEr
                                                                    ^
TypeError: Super expression must either be null or a function, not object
    at _inherits (/home/bot/git/DiscordBot/node_modules/discord.js/lib/Voice/StreamIntent.js:9:113)
    at /home/bot/git/DiscordBot/node_modules/discord.js/lib/Voice/StreamIntent.js:16:2
    at Object.<anonymous> (/home/bot/git/DiscordBot/node_modules/discord.js/lib/Voice/StreamIntent.js:25:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bot/git/DiscordBot/node_modules/discord.js/lib/Voice/VoiceConnection.js:38:21)

**Comment by abalabahaha** [comment]
Update nodejs to 0.12.7 or higher

**Comment by juhamoo** [comment]
Thanks, upgraded to a proper version and the launch seems to go through without errors.

I'm getting a Disconnected!-message now though, with no warnings / errors

 % node --version
v0.12.9

% node discord_bot.js
Disconnected!

If I copy / paste the login information for Discord from auth.json I can login with them OK, so the issue isn't wrong login info either. Any ideas?

**Comment by juhamoo** [comment]
Disregard, was network issues which seem to have sorted themselves out.

Thanks again for help.
