### ISSUE TITLE
Cannot load Wolfram module

### ISSUE THREAD

**Issue by xmx1024** [chalda/DiscordBot#56]
`couldn't load wolfram plugin!
Error: Could not locate the bindings file. Tried:
 → /home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/build/xmljs.node
 → /home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/build/Debug/xmljs.node
 → /home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/build/Release/xmljs.node
 → /home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/out/Debug/xmljs.node
 → /home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/Debug/xmljs.node
 → /home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/out/Release/xmljs.node
 → /home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/Release/xmljs.node
 → /home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/build/default/xmljs.node
 → /home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/compiled/4.3.0/linux/x64/xmljs.node
    at bindings (/home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/spencer/DiscordBot/node_modules/wolfram/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:410:26)
Couldn't load rss.json. See rss.json.example if you want rss feed commands. error: Error: Cannot find module './rss.json'
Ready to begin! Serving in 29 channels`

**Comment by Einarin** [comment]
Should be fixed by #82
