### ISSUE TITLE
perm command is broken

### ISSUE THREAD

**Issue by Einarin** [chalda/DiscordBot#65]
When invoked it returns:
```
ReferenceError: msg is not defined
    at resolveUser (plugins/Moderation/moderation.js:23:13)
    at Object.exports.perm.process (plugins/Moderation/moderation.js:42:14)
    at Client.<anonymous> (discord_bot.js:707:9)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at WebSocket.websocket.onmessage (node_modules/discord.js/lib/Client/InternalClient.js:1261:16)
    at WebSocket.onMessage (node_modules/ws/lib/WebSocket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (node_modules/ws/lib/WebSocket.js:816:10)
```

**Comment by Einarin** [comment]
I disabled the Moderation package in #82 because nothing in it worked.

**Comment by Einarin** [comment]
See #84
