### ISSUE TITLE
Errors everywhere...

### ISSUE THREAD

**Issue by XxPoNaGeXx** [chalda/DiscordBot#75]
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\XxPoNaGeXx>cd C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master

C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master>node discord_bot.js
couldn't load youtube plugin!
Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master\youtube_plugin.js:3:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
couldn't load wolfram plugin!
Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master\wolfram_plugin.js:2:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Please create an auth.json like auth.json.example with at least an email and password.
C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master\auth.json.js:2
        "email" : "kyleboyce8@me.com",
                ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master\discord_bot.js:26:20)
    at Module._compile (module.js:541:32)

C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master>node discord_bot.js
couldn't load youtube plugin!
Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master\youtube_plugin.js:3:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
couldn't load wolfram plugin!
Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master\wolfram_plugin.js:2:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Please create an auth.json like auth.json.example with at least an email and password.
C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master\auth.json.js:2
        "email" : "kyleboyce8@me.com",
                ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master\discord_bot.js:26:20)
    at Module._compile (module.js:541:32)

C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master>

C:\Users\XxPoNaGeXx\Desktop\DiscordBot-master\DiscordBot-master>

**Comment by chalda** [comment]
auth.json.js => should just be auth.json
also check your file you might be missing a comma

**Comment by DerfOh** [comment]
I agree, looks to be a comma missing in your auth.json just above the email field.

**Comment by chalda** [comment]
@notetoself: add a json linter as a grunt task

**Comment by Einarin** [comment]
Closing due to inactivity
