### ISSUE TITLE
Keeps asking me to create auth.json

### ISSUE THREAD

**Issue by ryandomasta** [chalda/DiscordBot#95]
Starting DiscordBot
Node version: v6.9.1
Discord.js version: 9.3.1
couldn't load youtube plugin!
SyntaxError: /Users/Ryan/Desktop/DiscordBot/DiscordBot-master/auth.json: Unexpected token \ in JSON at position 1
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Ryan/Desktop/DiscordBot/DiscordBot-master/youtube_plugin.js:3:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
couldn't load wolfram plugin!
SyntaxError: /Users/Ryan/Desktop/DiscordBot/DiscordBot-master/auth.json: Unexpected token \ in JSON at position 1
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Ryan/Desktop/DiscordBot/DiscordBot-master/wolfram_plugin.js:2:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
Please create an auth.json like auth.json.example with a bot token or an email and password.
SyntaxError: /Users/Ryan/Desktop/DiscordBot/DiscordBot-master/auth.json: Unexpected token \ in JSON at position 1
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Ryan/Desktop/DiscordBot/DiscordBot-master/discord_bot.js:41:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by ryandomasta** [comment]
bump

**Comment by Einarin** [comment]
This is due to the auth.json file being invalid
